# Generated by Django 4.1.2 on 2022-12-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffickingapp', '0002_alter_person_age_at_missing_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ManyToManyField(blank=True, to='traffickingapp.person')),
            ],
        ),
    ]
